platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((readonly_private_ecr_repo_name))
    tag: di-toolbox-latest
    aws_access_key_id: ((readonly_access_key_id))
    aws_secret_access_key: ((readonly_secret_access_key))
    aws_session_token: ((readonly_session_token))
    aws_region: eu-west-2
params:
  SMOKETESTER_PASSWORD: ((smoke-tester-password-integration))
outputs:
  - name: hashed-password
run:
  path: /bin/bash
  args:
    - -euc
    - |
      echo -n "${SMOKETESTER_PASSWORD}" | argon2 $(openssl rand -hex 32) -e -id -v 13 -k 15360 -t 2 -p 1 > hashed-password/hashed-password.txt